# This is a sample build configuration for Python.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Dockerhub as your build environment.
image: python:3.6

pipelines:
  default:
    - step:
        name: 'build and test'
        script:
          - python --version
          - pip --version
          - pip install -U flake8
          - python -m flake8 --show-source signac/
          - python setup.py build
          - python -m unittest discover tests/ -v
  branches:
    master:
      - step:
          name: 'build and test'
          image: themattrix/tox
          services:
            - mongo
          script:
            - python3.6 --version
            - pip3.6 --version
            - pip3.6 install -U coverage
            - python3.6 -m coverage --version
            - pip3.6 install -U flake8
            - python3.6 -m flake8 --show-source signac/
            - python3.6 setup.py build
            - python3.6 -m unittest discover tests/ -v
            - pip3.6 install -U pymongo
            - python3.6 -m signac config -l host testing
            - tox --version
            - tox
            - python3.6 -m coverage report -i --include="signac*"
    develop:
      - step:
          name: 'build and test'
          image: themattrix/tox
          services:
            - mongo
          script:
            - python3.6 --version
            - pip3.6 --version
            - pip3.6 install -U coverage
            - python3.6 -m coverage --version
            - pip3.6 install -U flake8
            - python3.6 -m flake8 --show-source signac/
            - python3.6 setup.py build
            - python3.6 -m unittest discover tests/ -v
            - pip3.6 install -U pymongo
            - python3.6 -m signac config -l host testing
            - tox --version
            - tox
            - python3.6 -m coverage report -i --include="signac*"
    release-*:
      - step:
          name: 'build and test'
          image: themattrix/tox
          services:
            - mongo
          script:
            - python3.6 --version
            - pip3.6 --version
            - pip3.6 install -U coverage
            - python3.6 -m coverage --version
            - pip3.6 install -U flake8
            - python3.6 -m flake8 --show-source signac/
            - python3.6 setup.py build
            - python3.6 -m unittest discover tests/ -v
            - pip3.6 install -U pymongo
            - python3.6 -m signac config -l host testing
            - tox --version
            - tox
            - python3.6 -m coverage report -i --include="signac*"
            - python -c "import json; json.load(open('.zenodo.json'))"
     - step:
          name: 'test-deploy'
          image: python:3.6
          script:
            - python --version
            - python -m pip --version
            - python -m pip install -U twine wheel setuptools
            - python -m twine --version
            - python -m wheel version
            - python -c "import json; json.load(open('.zenodo.json'))"
            - bash .test-deploy.bash
  tags:
   v*:
     - step:
          name: 'build and test'
          image: themattrix/tox
          services:
            - mongo
          script:
            - python3.6 --version
            - pip3.6 --version
            - pip3.6 install -U twine
            - python3.6 -m twine --version
            - pip3.6 install -U coverage
            - python3.6 -m coverage --version
            - pip3.6 install -U flake8
            - python3.6 -m flake8 --show-source signac/
            - python3.6 setup.py build
            - python3.6 -m unittest discover tests/ -v
            - pip3.6 install -U pymongo
            - python3.6 -m signac config -l host testing
            - tox --version
            - tox
            - python3.6 -m coverage report -i --include="signac*"
     - step:
          name: 'deploy'
          image: python:3.6
          script:
            - python --version
            - python -m pip --version
            - python -m pip install -U twine wheel setuptools
            - python -m twine --version
            - python -m wheel version
            - python -c "import json; json.load(open('.zenodo.json'))"
            - bash .deploy.bash

definitions:
  services:
    mongo:
      image: mongo
