# This is a sample build configuration for Python.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Dockerhub as your build environment.
image: python:3.6

pipelines:
  default:
    - step:
        name: 'build and test (py36)'
        script:
          - python --version
          - pip --version
          - pip install -U flake8
          - python -m flake8 --show-source signac/
          - python setup.py build
          - python -m unittest discover tests/ -v
  branches:
    release/*:
      - step:
          name: 'build and test (py36)'
          script:
            - python --version
            - pip --version
            - pip install -U flake8
            - python -m flake8 --show-source signac/
            - python setup.py build
            - python -m unittest discover tests/ -v
      - step:
          name: 'build and test (py27-3x)'
          image: themattrix/tox
          services:
            - mongo
          script:
            - python3.6 --version
            - pip3.6 --version
            - pip3.6 install -U coverage flake8 pymongo
            - python3.6 -m coverage --version
            - python3.6 -m flake8 --show-source signac/
            - python3.6 setup.py build
            - python3.6 -m signac config -l host testing
            - tox --version
            - tox
            - python3.6 -m coverage report -i --include="signac*"
      - step:
          name: 'check zenodo metadata'
          script:
            - python -c "import json; json.load(open('.zenodo.json'))"
      - step:
          name: 'check references.bib'
          script:
            - python -c "import pybtex; print(pybtex.format_from_file(open('references.bib'), style='unsrt', output_backend='text'))"
      - step:
          name: 'deploy-test.pypi.org'
          image: python:3.6
          deployment: test
          script:
            - python --version
            - python -m pip --version
            - python -m pip install -U twine wheel setuptools
            - python -m twine --version
            - python -m wheel version
            - bash .test-deploy.bash
  tags:
   v*:
      - step:
          name: 'check zenodo metadata'
          script:
            - python -c "import json; json.load(open('.zenodo.json'))"
      - step:
          name: 'build and test (py36)'
          script:
            - python --version
            - pip --version
            - pip install -U flake8
            - python -m flake8 --show-source signac/
            - python setup.py build
            - python -m unittest discover tests/ -v
      - step:
          name: 'build and test (py27-3x)'
          image: themattrix/tox
          services:
            - mongo
          script:
            - python3.6 --version
            - pip3.6 --version
            - pip3.6 install -U coverage flake8 pymongo
            - python3.6 -m coverage --version
            - python3.6 -m flake8 --show-source signac/
            - python3.6 setup.py build
            - python3.6 -m signac config -l host testing
            - tox --version
            - tox
            - python3.6 -m coverage report -i --include="signac*"
      - step:
          name: 'deploy-pypi.org'
          image: python:3.6
          deployment: production
          script:
            - python --version
            - python -m pip --version
            - python -m pip install -U twine wheel setuptools
            - python -m twine --version
            - python -m wheel version
            - bash .deploy.bash

definitions:
  services:
    mongo:
      image: mongo
